twitter-to-kafka-service:
  twitter-service:
    twitter-keywords:
      - Java
      - Kotlin
      - Australian
      - Japan
    enable-mock-tweets: true
    mock-min-tweet-length: 5
    mock-max-tweet-length: 15
    mock-sleep-ms: 10000

